FROM python:3.9.18-alpine3.18

# Make a directory
RUN mkdir server

# Copy the requirements.txt from the local folder to the image
COPY requirements.txt server/

# Install dependencies
RUN cd server
RUN pip install -r requirements.txt

CMD echo "Python packages installed"