# Generates a plot and statistics for the number of entities to which a token belongs
import matplotlib.pyplot as plt
import pandas as pd
import pickle

if __name__ == "__main__":

    # File generated by the LMDB lookup
    filepath = "./data/token-to-count.pickle"

    # Read the file
    with open(filepath, "rb") as fp:
        token_to_count = pickle.load(fp)

    print(f"Number of tokens: {len(token_to_count)}")

    # Make a dataframe
    data = {"token": token_to_count.keys(), "count": token_to_count.values()}
    df = pd.DataFrame(data)

    # Maximum number of entities for a token
    max_count = max(df["count"])
    most_frequent_tokens = list(df[df["count"] == max_count]["token"])
    print(f"Most frequent token(s) with count={max_count}: {most_frequent_tokens}")

    # Plot a histogram of the counts
    plt.hist(df["count"])
    plt.xlabel("Number of entities")
    plt.ylabel("Count")
    plt.title("Histogram of the number of entities in which a given token appears")
    plt.show()

    # Plot the token vs its count
    n = min(50, len(token_to_count))
    df.sort_values(by="count", ascending=False, inplace=True)
    counts = df.head(n)["count"].to_list()
    plt.bar(range(n), counts)
    plt.xticks(range(n), df.head(n)["token"].to_list(), rotation="vertical")
    plt.xlabel("Token")
    plt.ylabel("Number of entities")
    plt.show()
