/* Grammar rules 

   A sentence is constructed in the form:
   <article> <noun> <verb>

   The clauses generated by Prolog can be seen:
   ?- listing(article).
   article(A, B) :-
      (   A=[a|B]
      ;   A=[the|B]
   ).

   Test:
   ?- s('the cat ran').
   true .
*/

/* Define the grammar */
sentence --> article, noun, verb.
article --> [a]; [the].
noun --> [dog]; [cat]; [girl]; [boy].
verb --> [ran]; [talked]; [slept].

/* Split a string and see if the tokens form a sentence*/
s(String) :- 
    concat_atom(Tokens, ' ', String),  % Tokens is a list of tokens
    sentence(Tokens, []).
